const data = {
    product:[
        {
            _id:'1',
            name:'Shopping',
            category:'Hood',
            image:'./images/product-1.jpg',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Lasada',
            category:'Hood',
            image:'./images/product-2.jpg',
            price:300,
            brand:'Lasada',
            rating:5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'shoppee',
            category:'Hood',
            image:'./images/product-3.jpg',
            price:200,
            brand:'shoppee',
            rating:4,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'kerry',
            category:'pants',
            image:'./images/product-4.jpg',
            price:100,
            brand:'kerry',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'ems',
            category:'pants',
            image:'./images/product-5.jpg',
            price:500,
            brand:'ems',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
    ],
};

export default data;
